<?php declare( strict_types=1 );
/*
 * Copyright (c) 2022 Automattic, Inc.
 *
 * This file is part of the Automattic Domain Services Client library.
 *
 * The Automattic Domain Services Client library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program;
 * if not, see https://www.gnu.org/licenses.
 */

namespace Automattic\Domain_Services_Client\Entity;

use Automattic\Domain_Services_Client\{Exception};

/**
 * Represents a contact ID
 *
 * - Contact IDs are generated by creating new contacts after submitting `Contact_Information`
 * - `Domain_Contact` can be either represented as a contact ID or as contact information, but not both.
 *
 * @see Domain_Contact
 */
class Contact_Id {
	/**
	 * The contact ID
	 *
	 * @var string
	 */
	private string $contact_id;

	/**
	 * Constructs a `Contact_Id` entity
	 *
	 * @param string $contact_id
	 *
	 * @throws Exception\Entity\Invalid_Value_Exception
	 */
	public function __construct( string $contact_id ) {
		$contact_id_parts = explode( ':', $contact_id, 2 );

		if ( 2 !== count( $contact_id_parts ) ) {
			throw new Exception\Entity\Invalid_Value_Exception( __CLASS__, 'Invalid contact ID format' );
		}

		$this->contact_id = $contact_id;
	}

	/**
	 * Returns the string representation of the contact ID
	 *
	 * @internal
	 *
	 * @return string
	 */
	public function __toString(): string {
		return $this->get_contact_id();
	}

	/**
	 * Returns the contact ID
	 *
	 * @return string
	 */
	public function get_contact_id(): string {
		return $this->contact_id;
	}
}
