<?php declare( strict_types=1 );
/*
 * Copyright (c) 2022 Automattic, Inc.
 *
 * This file is part of the Automattic Domain Services Client library.
 *
 * The Automattic Domain Services Client library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program;
 * if not, see https://www.gnu.org/licenses.
 */

namespace Automattic\Domain_Services\Response;

trait Data_Trait {
	private array $data;

	/**
	 * `Response` object constructor
	 *
	 * @param array $data
	 */
	final public function __construct( array $data = [] ) {
		$this->data = $data;
	}

	/**
	 * Returns the response value for the given key, if it exists.
	 *
	 * @param string $key
	 * @return array|mixed|null
	 */
	final public function get_data_by_key( string $key ) {
		$key_parts = explode( '.', $key );
		$data = $this->data;
		foreach ( $key_parts as $key_part ) {
			$data = $data[ $key_part ] ?? null;
		}
		return $data;
	}

	/**
	 * Gets the response status code
	 *
	 * @return int
	 * @see Code
	 */
	final public function get_status(): int {
		return $this->get_data_by_key( 'status' );
	}

	/**
	 * Gets the response status description
	 *
	 * @return string
	 * @see Code::DESCRIPTION
	 */
	final public function get_status_description(): string {
		return $this->get_data_by_key( 'status_description' );
	}

	/**
	 * Gets whether the request succeeded.
	 *
	 * @return bool
	 */
	final public function is_success(): bool {
		return $this->get_data_by_key( 'success' );
	}

	/**
	 * Gets the client transaction ID that was sent with the request. Useful for logging and debugging.
	 *
	 * @return string
	 */
	final public function get_client_txn_id(): string {
		return $this->get_data_by_key( 'client_txn_id' );
	}

	/**
	 * Gets the server transaction ID that was generated by the Automattic Domain Services back-end for this request.
	 * Useful for logging and debugging.
	 *
	 * @return string
	 */
	final public function get_server_txn_id(): string {
		return $this->get_data_by_key( 'server_txn_id' );
	}

	/**
	 * Gets the timestamp this response was generated.
	 *
	 * @return int
	 */
	final public function get_timestamp(): int {
		return $this->get_data_by_key( 'timestamp' );
	}

	/**
	 * Gets the runtime (in seconds) the processing of this command took on the back-end.
	 *
	 * @return float
	 */
	final public function get_runtime(): float {
		return $this->get_data_by_key( 'runtime' );
	}
}
